for obj in objects where isGroupHead obj do setGroupOpen obj on

for obj in selection where isKindOf obj Helper

for eachLight in lights where isProperty eachLight #intensity do eachLight.intensity = 1000






apropos
getPropNames
isGroupHead
isKindOf
isProperty
getProperty
setProperty
hasProperty 




BOX3 values (also boolean math)
http://creativescratchpad.blogspot.com/2017/05/undocumented-maxscript-features.html